#!/bin/bash

curl -X PUT http://localhost:8192/authors/4577cf3e-e775-4c93-9533-9a404b05df9a -H 'Content-Type: application/json' -d '{"firstName":"newname","lastName":"pupkin"}'
# 4577cf3e-e775-4c93-9533-9a404b05df9a