#!/bin/bash

curl -X PUT http://localhost:8192/books/d90cb11c-2bb3-436b-948a-4cefdb389229 -H 'Content-Type: application/json' -d '{"name":"Some Book","authorId":"780c2141-05c7-48f0-9e86-b15f6fdd15ab","releaseDate":"2034-01-01T00:00:01Z","genre":"HORROR"}'
