#!/bin/bash

curl -X PUT http://localhost:8192/books/780c2141-05c7-48f0-9e86-b15f6fdd15ab -H 'Content-Type: application/json' -d '{"name":"Some Book","authorId":"780c2141-05c7-48f0-9e86-b15f6fdd15ab","releaseDate":"2033-01-01T00:00:01Z","genre":"HORROR"}'
