#!/bin/bash

curl -X POST http://192.168.6.30:8192/projects -H 'Content-Type: application/json' -d '{"creationDate":"2022-01-01T00:00:00Z","editDate":"2022-01-01T00:00:00Z","name":"someproject","description":"description"}'
# a26b831a-6454-445a-8034-ca213f18ff8e