#!/bin/bash

curl -X POST http://192.168.6.30:8192/tasks -H 'Content-Type: application/json' -d '{"creationDate":"2022-01-01", "editDate":"2022-01-01", "header":"header", "description": "description", "priority":"HIGH", "temporaryMark":"1","project":"a26b831a-6454-445a-8034-ca213f18ff8e", "userCreator":"6b85027a-2bbb-4101-9973-bd2cbdc3e81c", "userExecutor":"6b85027a-2bbb-4101-9973-bd2cbdc3e81c"}'
